name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_IMAGE_NAME: avito-parser
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  VERSION: ${{ github.sha }}
  SHORT_VERSION: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
            mkdir -p ${{ secrets.APP_LOCATION }} && \
            cd ${{ secrets.APP_LOCATION }} && \
            echo 'URL_AVITO=${{ secrets.URL_AVITO }}' > .env && \
            echo 'CHAT_ID_TG=${{ secrets.CHAT_ID_TG }}' >> .env && \
            echo 'TG_TOKEN=${{ secrets.TG_TOKEN }}' >> .env && \
            echo 'NUM_ADS_AVITO=${{ secrets.NUM_ADS_AVITO }}' >> .env && \
            echo 'FREQ_AVITO=${{ secrets.FREQ_AVITO }}' >> .env && \
            echo 'KEYS_AVITO=${{ secrets.KEYS_AVITO }}' >> .env && \
            echo 'MAX_PRICE_AVITO=${{ secrets.MAX_PRICE_AVITO }}' >> .env && \
            echo 'MIN_PRICE_AVITO=${{ secrets.MIN_PRICE_AVITO }}' >> .env && \
            echo 'GEO_AVITO=${{ secrets.GEO_AVITO }}' >> .env && \
            echo 'PROXY_AVITO=${{ secrets.PROXY_AVITO }}' >> .env && \
            echo 'PROXY_CHANGE_IP_AVITO=${{ secrets.PROXY_CHANGE_IP_AVITO }}' >> .env && \
            echo 'NEED_MORE_INFO_AVITO=${{ secrets.NEED_MORE_INFO_AVITO }}' >> .env && \
            echo 'DEBUG_MODE_AVITO=${{ secrets.DEBUG_MODE_AVITO }}' >> .env && \
            echo 'FAST_SPEED_AVITO=${{ secrets.FAST_SPEED_AVITO }}' >> .env && \
            echo 'KEYS_BLACK_AVITO=${{ secrets.KEYS_BLACK_AVITO }}' >> .env && \
            echo 'MAX_VIEW_AVITO=${{ secrets.MAX_VIEW_AVITO }}' >> .env && \
            echo 'version: \"3\"' > docker-compose.yml && \
            echo 'services:' >> docker-compose.yml && \
            echo '  avito-parser:' >> docker-compose.yml && \
            echo '    image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.VERSION }}' >> docker-compose.yml && \
            echo '    container_name: avito-parser' >> docker-compose.yml && \
            echo '    restart: unless-stopped' >> docker-compose.yml && \
            echo '    env_file: .env' >> docker-compose.yml && \
            docker compose pull && \
            docker compose down && \
            docker compose up -d && \
            docker logs avito-parser
          "